# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cambermast
email: chungisutest@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A personal tech blog built with Jekyll and hosted on GitHub Pages. 
  Sharing tutorials, code snippets, and insights on web development, 
  programming, and static site generation.
baseurl: "/github-pages-with-docker" # the subpath of your site, e.g. /blog
url: "https://spaceboyblog.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: spaceboy
github_username:  Spaceboyblog

# Fields minima uses, but are not defaulted with the jekyll new command.
# Author is the default for posts, the Atom feed, and is used in the footer.
author: S.Y.Chung
linkedin_username: williamraymond
youtube_username: ProjectNationBill

# Add this to _config.xml
# New fields not defaulted by jekyll-new with the minima theme
# Add a copyright. A copyright symbol and year will be added automatically
copyright: "SunIl LLC"

# Build settings
markdown: kramdown
# Remove minima theme as it is now a regular theme
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
